### ISSUE TITLE
No way to cache models between executions

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-ollama#11]
### Describe the issue

Right now, the Ollama plugin uses the Docker Task Runner with the `ollama/ollama` image to work. This means that any images that are pulled are only stored for that execution as the container is destroyed at the end. This means the execution times are really long as it has to pull models every single execution.

![Image](https://github.com/user-attachments/assets/3fc34d9c-1573-417c-9713-6e407804ad7c)

In my recent testing for an upcoming video, I'm seeing it take multiple minutes, whereas OpenAI ChatCompletion as a replacement for Ollama takes less than a minute.

One way to get around this is to install ollama on the kestra host/container and use a process task runner but was hoping there could be a way to keep models installed like we can cache python dependencies. 

Example task:

```yaml
id: ollama_plugin
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    commands:
      - ollama pull gemma3:1b
      - ollama run gemma3:1b "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt
```

### Environment

- Kestra Version: 0.23.3 EE

**Comment by Malaydewangan09** [comment]
@anna-geller 

```yaml
id: ollama_teest
namespace: dev

tasks:
  - id: simple_mount_check
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    enableModelCaching: true
    modelCachePath: /Users/malay/.ollama
    commands:
      - ollama run gemma3:1b "Tell me a joke about AI" > completion.txt

```
I've tried something by adding these new properties
```yaml
   enableModelCaching: true
   modelCachePath: /Users/malay/.ollama
```
Though this is similar to mounting volumes but inside an Ollama task only.
Since Ollama model images are not regular OCI based images, they are not automatically handled by the Docker engine.
Makes sense?

**Comment by Malaydewangan09** [comment]
I mean, yes we can have a default path where ollama by deafult stores its models
but we need to give user a property, what if user want to use  a diff location on the host no rather than default one no?

**Comment by Malaydewangan09** [comment]
Using host property
```yaml
id: volume_mount_test
namespace: dev

tasks:
  - id: ollama_host
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    host: "http://host.docker.internal:11434"  
    commands:
      - ollama run gemma3:1b "Tell me a joke about AI" > completion.txt

    outputFiles:
      - completion.txt
```
