### ISSUE TITLE
`llama2` fails

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-ollama#12]
### Describe the issue

This workflow works with `gemma3:1b` but fails with `llama2:7b`. `gemma3:1b` is a lot smaller. Does this mean there's some sort of limit of size of model with Kestra due to docker restrictions on that system?

More information to be added.

```yaml
id: ollama_plugin
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    commands:
      - ollama pull llama2:7b
      - ollama run llama2:7b "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt
```

### Environment

- Kestra Version: 0.23.3 EE

**Comment by anna-geller** [comment]
> You should have at least 8 GB of RAM available to run the 7B models

if you have enough memory, it should work, so likely some memory allocation issue to the container/docker resources I'd assume. I couldn't reproduce on my Mac running Kestra in a single container on H2 as in Getting started (but using Collima, not docker desktop):

![Image](https://github.com/user-attachments/assets/d07d8b12-248e-4f6a-840c-5dd18ae3f4c5)

I'd guess try to allocate at least 8GB memory to your Docker setup and see if that helped?

**Comment by wrussell1999** [comment]
When removing the model at the end, there is no output generated. The file is blank.

```yaml
id: ollama_plugin
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    commands:
      - ollama pull gemma3:1b
      - ollama run gemma3:1b "{{ inputs.prompt }}" > completion.txt
      - ollama rm gemma3:1b
    outputFiles:
      - completion.txt
```

![Image](https://github.com/user-attachments/assets/242eff02-722f-489d-82a8-3f5a1318ff06)

**Comment by wrussell1999** [comment]
I can confirm that I was able to resolve this by upping my colima docker config to 16GB. `llama2:7b` worked and produced an output file. However, it still took 5 minutes so investigating the issue.

Also using `shell.Commands` won't work to test this as `ollama serve` means the task never ends as its starts a server.

**Comment by Malaydewangan09** [comment]
Could you, add this to your config and let me know if this changes things, please?

```yaml
plugins:
  configurations:
    - type: io.kestra.plugin.scripts.runner.docker.Docker
      values:
        volume-enabled: true
```

**Comment by Malaydewangan09** [comment]
@wrussell1999, Could you add this to your config and let me know if this works for you, please?
This allows us to enable volume mounting in our task runner.
I think we need to add this in the plugin property description. WDYT?

```yaml
plugins:
  configurations:
    - type: io.kestra.plugin.scripts.runner.docker.Docker
      values:
        volume-enabled: true
```

So now we have 2 options. if you `enableModelCaching` , then after the first run it stores the model there
```yaml
id: ollama_plugins
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    enableModelCaching: true
    commands:
      - ollama run smollm:135m "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt

```

<img width="1118" height="37" alt="Image" src="https://github.com/user-attachments/assets/6ac107ea-3dca-42d2-ac28-a2fc68be916c" />


<hr> 

- Now, if you have any models downloaded locally, you could use `modelCachePath` along with `enableModelCaching` and provide a host path where your ollama models are stored; this will take those models and use them

For this flow I pulled gemma3:1b only locally, then using `modelCachepath`
```yaml
id: ollama_plugins
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    enableModelCaching: true
    modelCachePath: /Users/malay/.ollama
    commands:
      - ollama run gemma3:1b "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt
```

<img width="1118" height="37" alt="Image" src="https://github.com/user-attachments/assets/9ba24892-f87b-4f98-809f-3951f61724b8" />

**Comment by wrussell1999** [comment]
This is working now! Thanks so much. I will also try the `modelCachePath` property to ensure the behaviour is as expected but the caching works great now once adding to the config.

<img width="1288" height="319" alt="Image" src="https://github.com/user-attachments/assets/48c64b0b-00ee-4db9-8d8e-ab31bdf934f9" />

Is there a way to do this directly in the task runner of the task?

Something like this? (it doesn't allow it currently but could be worth looking into? WDYT?)
```yaml
id: ollama_plugin
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    taskRunner: 
      type: io.kestra.plugin.scripts.runner.docker.Docker
      volume-enabled: true
    enableModelCaching: true
    commands:
      - ollama run gemma3:1b "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt
```

**Comment by Malaydewangan09** [comment]
Yep, definitely worth looking into.
Thanks!

**Comment by wrussell1999** [comment]
Can confirm, `modelCachePath` works as expected!

```yaml
id: ollama_plugin
namespace: company.team

inputs:
  - id: prompt
    type: STRING
    defaults: Tell me a joke about AI

tasks:
  - id: hello
    type: io.kestra.plugin.ollama.cli.OllamaCLI
    enableModelCaching: true
    modelCachePath: /Users/wrussell/.ollama
    commands:
      - ollama run gemma3:1b "{{ inputs.prompt }}" > completion.txt
    outputFiles:
      - completion.txt
```

Kestra downloaded a model I didn't have, and now it shows up on my local machine too.
<img width="881" height="502" alt="Image" src="https://github.com/user-attachments/assets/4e1bf2c6-30a5-4455-b0c8-2ffd73f134f7" />
